import type { RecordSpec } from '../../../types'

export const FEBRABAN_C240_HEADER_ARQ: RecordSpec = {
  id: 'febraban-c240-header-arquivo-0000',
  layout: 'c240',
  recordType: '0000-0',
  label: 'Header arquivo CNAB240',
  lineLength: 240,
  fields: [
    { id: 'codigo_banco', label: 'Código banco', start: 1, end: 3, type: 'numeric', issueCode: 'F240_HDR_BANCO' },
    { id: 'lote', label: 'Lote', start: 4, end: 7, type: 'enum', enum: ['0000'] },
    { id: 'tipo_registro', label: 'Tipo registro', start: 8, end: 8, type: 'enum', enum: ['0'] },
    { id: 'uso_febraban', label: 'Uso FEBRABAN', start: 9, end: 17, type: 'filler', required: false },
    { id: 'tipo_inscricao', label: 'Tipo inscrição', start: 18, end: 18, type: 'enum', enum: ['1', '2'] },
    { id: 'cnpj_cpf', label: 'CNPJ/CPF', start: 19, end: 32, type: 'numeric' },
    { id: 'convenio', label: 'Convênio', start: 33, end: 52, type: 'alphanumeric', bankOverride: true, required: false },
    { id: 'agencia', label: 'Agência', start: 53, end: 57, type: 'numeric' },
    { id: 'dv_agencia', label: 'DV agência', start: 58, end: 58, type: 'alphanumeric', required: false },
    { id: 'conta', label: 'Conta', start: 59, end: 70, type: 'numeric' },
    { id: 'dv_conta', label: 'DV conta', start: 71, end: 71, type: 'alphanumeric', required: false },
    { id: 'dv_ag_conta', label: 'DV ag/conta', start: 72, end: 72, type: 'alphanumeric', required: false },
    { id: 'nome_empresa', label: 'Nome empresa', start: 73, end: 102, type: 'alpha' },
    { id: 'nome_banco', label: 'Nome banco', start: 103, end: 132, type: 'alpha' },
    { id: 'uso_febraban2', label: 'Uso FEBRABAN', start: 133, end: 142, type: 'filler', required: false },
    { id: 'remessa_retorno', label: 'Remessa/Retorno', start: 143, end: 143, type: 'enum', enum: ['1'], issueCode: 'F240_HDR_REM_RET' },
    { id: 'data_geracao', label: 'Data geração', start: 144, end: 151, type: 'date', format: 'DDMMAAAA' },
    { id: 'hora_geracao', label: 'Hora geração', start: 152, end: 157, type: 'time' },
    { id: 'numero_arquivo', label: 'Nº sequencial arquivo', start: 158, end: 163, type: 'numeric' },
    { id: 'versao_layout', label: 'Versão layout', start: 164, end: 166, type: 'numeric' },
    { id: 'densidade', label: 'Densidade', start: 167, end: 171, type: 'numeric', required: false },
    { id: 'uso_exclusivo', label: 'Uso exclusivo', start: 172, end: 240, type: 'filler', required: false },
  ],
}

export const FEBRABAN_C240_HEADER_LOTE: RecordSpec = {
  id: 'febraban-c240-header-lote-0001',
  layout: 'c240',
  recordType: '0001-1',
  label: 'Header lote CNAB240',
  lineLength: 240,
  fields: [
    { id: 'codigo_banco', label: 'Código banco', start: 1, end: 3, type: 'numeric' },
    { id: 'lote', label: 'Lote', start: 4, end: 7, type: 'enum', enum: ['0001'] },
    { id: 'tipo_registro', label: 'Tipo registro', start: 8, end: 8, type: 'enum', enum: ['1'] },
    { id: 'operacao', label: 'Operação', start: 9, end: 9, type: 'enum', enum: ['R'], issueCode: 'F240_LOTE_OP' },
    { id: 'servico', label: 'Serviço', start: 10, end: 11, type: 'enum', enum: ['01'], issueCode: 'F240_LOTE_SERV' },
    { id: 'uso_febraban', label: 'Uso FEBRABAN', start: 12, end: 13, type: 'filler', required: false },
    { id: 'versao_lote', label: 'Versão layout lote', start: 14, end: 16, type: 'numeric' },
    { id: 'uso_febraban2', label: 'Uso FEBRABAN', start: 17, end: 17, type: 'filler', required: false },
    { id: 'tipo_inscricao', label: 'Tipo inscrição', start: 18, end: 18, type: 'enum', enum: ['1', '2'] },
    { id: 'cnpj_cpf', label: 'CNPJ/CPF', start: 19, end: 33, type: 'numeric' },
    { id: 'convenio', label: 'Convênio', start: 34, end: 53, type: 'alphanumeric', bankOverride: true, required: false },
    { id: 'agencia', label: 'Agência', start: 54, end: 58, type: 'numeric' },
    { id: 'dv_agencia', label: 'DV agência', start: 59, end: 59, type: 'alphanumeric', required: false },
    { id: 'conta', label: 'Conta', start: 60, end: 71, type: 'numeric' },
    { id: 'dv_conta', label: 'DV conta', start: 72, end: 72, type: 'alphanumeric', required: false },
    { id: 'dv_ag_conta', label: 'DV ag/conta', start: 73, end: 73, type: 'alphanumeric', required: false },
    { id: 'nome_cedente', label: 'Nome cedente', start: 74, end: 103, type: 'alpha' },
    { id: 'mensagem1', label: 'Mensagem 1', start: 104, end: 143, type: 'alpha', required: false },
    { id: 'mensagem2', label: 'Mensagem 2', start: 144, end: 183, type: 'alpha', required: false },
    { id: 'numero_remessa', label: 'Nº remessa', start: 184, end: 191, type: 'numeric' },
    { id: 'data_gravacao', label: 'Data gravação', start: 192, end: 199, type: 'date', format: 'DDMMAAAA' },
    { id: 'data_credito', label: 'Data crédito', start: 200, end: 207, type: 'date', format: 'DDMMAAAA', required: false },
    { id: 'uso_exclusivo', label: 'Uso exclusivo', start: 208, end: 240, type: 'filler', required: false },
  ],
}

export const FEBRABAN_C240_SEGMENTO_P: RecordSpec = {
  id: 'febraban-c240-segmento-p',
  layout: 'c240',
  recordType: '3P',
  label: 'Segmento P',
  lineLength: 240,
  fields: [
    { id: 'codigo_banco', label: 'Código banco', start: 1, end: 3, type: 'numeric' },
    { id: 'lote', label: 'Lote', start: 4, end: 7, type: 'numeric' },
    { id: 'tipo_registro', label: 'Tipo registro', start: 8, end: 8, type: 'enum', enum: ['3'] },
    { id: 'sequencial', label: 'Sequencial lote', start: 9, end: 13, type: 'numeric' },
    { id: 'segmento', label: 'Segmento', start: 14, end: 14, type: 'enum', enum: ['P'] },
    { id: 'uso_febraban', label: 'Uso FEBRABAN', start: 15, end: 15, type: 'filler', required: false },
    {
      id: 'codigo_movimento',
      label: 'Código movimento',
      start: 16,
      end: 17,
      type: 'enum',
      enumRef: 'bradesco-remessa-240',
      issueCode: 'F240_SEGP_MOV',
    },
    { id: 'agencia', label: 'Agência', start: 18, end: 22, type: 'numeric' },
    { id: 'dv_agencia', label: 'DV agência', start: 23, end: 23, type: 'alphanumeric', required: false },
    { id: 'conta', label: 'Conta', start: 24, end: 35, type: 'numeric' },
    { id: 'dv_conta', label: 'DV conta', start: 36, end: 36, type: 'alphanumeric', required: false },
    { id: 'dv_ag_conta', label: 'DV ag/conta', start: 37, end: 37, type: 'filler', required: false },
    { id: 'nosso_numero', label: 'Nosso número', start: 38, end: 57, type: 'alphanumeric', issueCode: 'F240_SEGP_NOSSO' },
    { id: 'carteira', label: 'Carteira', start: 58, end: 58, type: 'numeric' },
    { id: 'cadastramento', label: 'Cadastramento', start: 59, end: 59, type: 'enum', enum: ['1'], required: false },
    { id: 'documento', label: 'Tipo documento', start: 60, end: 60, type: 'alphanumeric', required: false },
    { id: 'emissao', label: 'Emissão bloqueto', start: 61, end: 61, type: 'alphanumeric', required: false },
    { id: 'distribuicao', label: 'Distribuição', start: 62, end: 62, type: 'alphanumeric', required: false },
    { id: 'numero_documento', label: 'Nº documento', start: 63, end: 77, type: 'alphanumeric' },
    { id: 'vencimento', label: 'Vencimento', start: 78, end: 85, type: 'date', format: 'DDMMAAAA', issueCode: 'F240_SEGP_VENC' },
    { id: 'valor', label: 'Valor nominal', start: 86, end: 100, type: 'money', issueCode: 'F240_SEGP_VALOR' },
    { id: 'resto', label: 'Demais campos P', start: 101, end: 240, type: 'filler', required: false },
  ],
}

export const FEBRABAN_C240_SEGMENTO_Q: RecordSpec = {
  id: 'febraban-c240-segmento-q',
  layout: 'c240',
  recordType: '3Q',
  label: 'Segmento Q',
  lineLength: 240,
  fields: [
    { id: 'codigo_banco', label: 'Código banco', start: 1, end: 3, type: 'numeric' },
    { id: 'lote', label: 'Lote', start: 4, end: 7, type: 'numeric' },
    { id: 'tipo_registro', label: 'Tipo registro', start: 8, end: 8, type: 'enum', enum: ['3'] },
    { id: 'sequencial', label: 'Sequencial lote', start: 9, end: 13, type: 'numeric' },
    { id: 'segmento', label: 'Segmento', start: 14, end: 14, type: 'enum', enum: ['Q'] },
    { id: 'uso_febraban', label: 'Uso FEBRABAN', start: 15, end: 15, type: 'filler', required: false },
    {
      id: 'codigo_movimento',
      label: 'Código movimento',
      start: 16,
      end: 17,
      type: 'enum',
      enumRef: 'bradesco-remessa-240',
    },
    { id: 'tipo_inscricao', label: 'Tipo inscrição', start: 18, end: 18, type: 'enum', enum: ['1', '2'] },
    { id: 'cpf_cnpj', label: 'CPF/CNPJ', start: 19, end: 33, type: 'numeric', issueCode: 'F240_SEGQ_CPF' },
    { id: 'nome', label: 'Nome sacado', start: 34, end: 73, type: 'alpha', issueCode: 'F240_SEGQ_NOME' },
    { id: 'endereco', label: 'Endereço', start: 74, end: 113, type: 'alpha', required: false },
    { id: 'bairro', label: 'Bairro', start: 114, end: 128, type: 'alpha', required: false },
    { id: 'cep', label: 'CEP', start: 129, end: 133, type: 'numeric' },
    { id: 'cep_sufixo', label: 'Sufixo CEP', start: 134, end: 136, type: 'numeric', required: false },
    { id: 'cidade', label: 'Cidade', start: 137, end: 151, type: 'alpha', required: false },
    { id: 'uf', label: 'UF', start: 152, end: 153, type: 'alpha', required: false },
    { id: 'resto', label: 'Avalista/resto', start: 154, end: 240, type: 'filler', required: false },
  ],
}

export const FEBRABAN_C240_TRAILER_LOTE: RecordSpec = {
  id: 'febraban-c240-trailer-lote-0001',
  layout: 'c240',
  recordType: '0001-5',
  label: 'Trailer lote CNAB240',
  lineLength: 240,
  fields: [
    { id: 'codigo_banco', label: 'Código banco', start: 1, end: 3, type: 'numeric' },
    { id: 'lote', label: 'Lote', start: 4, end: 7, type: 'enum', enum: ['0001'] },
    { id: 'tipo_registro', label: 'Tipo registro', start: 8, end: 8, type: 'enum', enum: ['5'] },
    { id: 'uso_febraban', label: 'Uso FEBRABAN', start: 9, end: 17, type: 'filler', required: false },
    { id: 'qtd_registros', label: 'Qtd registros lote', start: 18, end: 23, type: 'numeric', required: false },
    { id: 'resto', label: 'Totais/resto', start: 24, end: 240, type: 'filler', required: false },
  ],
}

export const FEBRABAN_C240_TRAILER_ARQ: RecordSpec = {
  id: 'febraban-c240-trailer-arquivo-9999',
  layout: 'c240',
  recordType: '9999-9',
  label: 'Trailer arquivo CNAB240',
  lineLength: 240,
  fields: [
    { id: 'codigo_banco', label: 'Código banco', start: 1, end: 3, type: 'numeric' },
    { id: 'lote', label: 'Lote', start: 4, end: 7, type: 'enum', enum: ['9999'] },
    { id: 'tipo_registro', label: 'Tipo registro', start: 8, end: 8, type: 'enum', enum: ['9'] },
    { id: 'uso_febraban', label: 'Uso FEBRABAN', start: 9, end: 17, type: 'filler', required: false },
    { id: 'qtd_lotes', label: 'Qtd lotes', start: 18, end: 23, type: 'numeric', required: false },
    { id: 'qtd_registros', label: 'Qtd registros', start: 24, end: 29, type: 'numeric', required: false },
    { id: 'resto', label: 'Uso exclusivo', start: 30, end: 240, type: 'filler', required: false },
  ],
}

export const FEBRABAN_C240_SPECS: RecordSpec[] = [
  FEBRABAN_C240_HEADER_ARQ,
  FEBRABAN_C240_HEADER_LOTE,
  FEBRABAN_C240_SEGMENTO_P,
  FEBRABAN_C240_SEGMENTO_Q,
  FEBRABAN_C240_TRAILER_LOTE,
  FEBRABAN_C240_TRAILER_ARQ,
]
