import type { RecordSpec } from '../../../types'

/** Header CNAB400 FEBRABAN — ACBr TACBrBancoClass.GerarRegistroHeader400 */
export const FEBRABAN_C400_HEADER_0: RecordSpec = {
  id: 'febraban-c400-header-0',
  layout: 'c400',
  recordType: '0',
  label: 'Header CNAB400',
  lineLength: 400,
  acbrRef: 'ACBrBoleto.pas:TACBrBancoClass.GerarRegistroHeader400',
  fields: [
    {
      id: 'tipo_registro',
      label: 'Identificação do registro',
      start: 1,
      end: 1,
      type: 'enum',
      enum: ['0'],
      issueCode: 'F400_HDR_TIPO_REG',
    },
    {
      id: 'tipo_arquivo',
      label: 'Identificação arquivo remessa',
      start: 2,
      end: 2,
      type: 'enum',
      enum: ['1'],
      issueCode: 'F400_HDR_TIPO_ARQ',
    },
    {
      id: 'literal_remessa',
      label: 'Literal REMESSA',
      start: 3,
      end: 9,
      type: 'alpha',
      issueCode: 'F400_HDR_LITERAL',
    },
    {
      id: 'codigo_servico',
      label: 'Código serviço',
      start: 10,
      end: 11,
      type: 'enum',
      enum: ['01'],
    },
    {
      id: 'literal_servico',
      label: 'Literal serviço',
      start: 12,
      end: 26,
      type: 'alpha',
    },
    {
      id: 'codigo_empresa',
      label: 'Código da empresa no banco',
      start: 27,
      end: 46,
      type: 'alphanumeric',
      bankOverride: true,
    },
    {
      id: 'nome_empresa',
      label: 'Nome da empresa',
      start: 47,
      end: 76,
      type: 'alpha',
      required: true,
    },
    {
      id: 'codigo_banco',
      label: 'Código do banco',
      start: 77,
      end: 79,
      type: 'numeric',
      pad: 'numeric',
      issueCode: 'F400_HDR_BANCO',
    },
    {
      id: 'nome_banco',
      label: 'Nome do banco',
      start: 80,
      end: 94,
      type: 'alpha',
    },
    {
      id: 'data_geracao',
      label: 'Data gravação',
      start: 95,
      end: 100,
      type: 'date',
      format: 'DDMMAA',
      issueCode: 'F400_HDR_DATA',
    },
    {
      id: 'brancos_101',
      label: 'Brancos',
      start: 101,
      end: 107,
      type: 'filler',
      required: false,
    },
    {
      id: 'codigo_parametro',
      label: 'Código parâmetro movimento',
      start: 108,
      end: 110,
      type: 'alphanumeric',
      required: false,
    },
    {
      id: 'numero_remessa',
      label: 'Número sequencial remessa',
      start: 111,
      end: 117,
      type: 'numeric',
      pad: 'numeric',
    },
    {
      id: 'brancos_118',
      label: 'Brancos',
      start: 118,
      end: 394,
      type: 'filler',
      required: false,
    },
    {
      id: 'sequencial',
      label: 'Sequencial registro',
      start: 395,
      end: 400,
      type: 'numeric',
      pad: 'numeric',
      issueCode: 'F400_HDR_SEQ',
    },
  ],
}

/** Trailer CNAB400 FEBRABAN */
export const FEBRABAN_C400_TRAILER_9: RecordSpec = {
  id: 'febraban-c400-trailer-9',
  layout: 'c400',
  recordType: '9',
  label: 'Trailer CNAB400',
  lineLength: 400,
  fields: [
    {
      id: 'tipo_registro',
      label: 'Identificação do registro',
      start: 1,
      end: 1,
      type: 'enum',
      enum: ['9'],
      issueCode: 'F400_TRL_TIPO',
    },
    {
      id: 'brancos',
      label: 'Brancos',
      start: 2,
      end: 394,
      type: 'filler',
      required: false,
    },
    {
      id: 'sequencial',
      label: 'Sequencial registro',
      start: 395,
      end: 400,
      type: 'numeric',
      pad: 'numeric',
      issueCode: 'F400_TRL_SEQ',
    },
  ],
}

export const FEBRABAN_SPECS: RecordSpec[] = [FEBRABAN_C400_HEADER_0, FEBRABAN_C400_TRAILER_9]
