import type { RecordSpec } from '../../../../types'

/** Detalhe CNAB400 BB (convênio ≤ 6, registro 1) — ACBrBancoBrasil.GerarRegistroTransacao400 */
export const BB_C400_DETALHE_1: RecordSpec = {
  id: 'cobBancoDoBrasil-c400-detalhe-1',
  layout: 'c400',
  recordType: '1',
  label: 'Detalhe BB CNAB400',
  lineLength: 400,
  bankId: 'cobBancoDoBrasil',
  acbrRef: 'ACBrBancoBrasil.pas:GerarRegistroTransacao400',
  fields: [
    { id: 'tipo_registro', label: 'Tipo registro', start: 1, end: 1, type: 'enum', enum: ['1'], issueCode: 'F400_DET_TIPO' },
    { id: 'tipo_inscricao_cedente', label: 'Tipo inscrição cedente', start: 2, end: 3, type: 'enum', enum: ['01', '02'] },
    { id: 'cnpj_cedente', label: 'CNPJ/CPF cedente', start: 4, end: 17, type: 'numeric' },
    { id: 'agencia', label: 'Agência', start: 18, end: 21, type: 'numeric' },
    { id: 'dv_agencia', label: 'DV agência', start: 22, end: 22, type: 'alphanumeric', required: false },
    { id: 'conta', label: 'Conta', start: 23, end: 30, type: 'numeric' },
    { id: 'dv_conta', label: 'DV conta', start: 31, end: 31, type: 'alphanumeric', required: false },
    { id: 'convenio', label: 'Convênio', start: 32, end: 37, type: 'numeric', issueCode: 'F400_BB_CONV' },
    { id: 'controle_participante', label: 'Controle participante', start: 38, end: 62, type: 'alphanumeric', required: false },
    { id: 'nosso_numero', label: 'Nosso número', start: 63, end: 74, type: 'alphanumeric', issueCode: 'F400_BB_NOSSO' },
    { id: 'zeros_prefixo', label: 'Zeros/brancos prefixo', start: 75, end: 81, type: 'alphanumeric', required: false },
    { id: 'ind_avalista_msg', label: 'Ind. avalista/mensagem', start: 82, end: 82, type: 'alphanumeric', required: false },
    { id: 'brancos_83', label: 'Brancos', start: 83, end: 85, type: 'filler', required: false },
    { id: 'modalidade', label: 'Modalidade carteira', start: 86, end: 88, type: 'numeric', required: false },
    { id: 'zeros_carteira', label: 'Zeros carteira', start: 89, end: 101, type: 'numeric', required: false },
    { id: 'tipo_cobranca', label: 'Tipo cobrança', start: 102, end: 106, type: 'alphanumeric', required: false },
    { id: 'carteira', label: 'Carteira', start: 107, end: 108, type: 'numeric', issueCode: 'F400_BB_CART' },
    {
      id: 'ocorrencia',
      label: 'Código ocorrência',
      start: 109,
      end: 110,
      type: 'enum',
      enumRef: 'bb-remessa-400',
      issueCode: 'F400_BB_OCORR',
    },
    { id: 'numero_documento', label: 'Número documento', start: 111, end: 120, type: 'alphanumeric', issueCode: 'F400_DET_DOC' },
    { id: 'vencimento', label: 'Vencimento', start: 121, end: 126, type: 'date', format: 'DDMMAA', issueCode: 'F400_DET_VENC' },
    { id: 'valor', label: 'Valor título', start: 127, end: 139, type: 'money', issueCode: 'F400_DET_VALOR' },
    { id: 'codigo_banco', label: 'Código banco', start: 140, end: 142, type: 'numeric' },
    { id: 'agencia_cobradora', label: 'Agência cobradora', start: 143, end: 146, type: 'numeric', required: false },
    { id: 'dv_ag_cobradora', label: 'DV ag. cobradora', start: 147, end: 147, type: 'alphanumeric', required: false },
    { id: 'especie', label: 'Espécie documento', start: 148, end: 149, type: 'numeric', required: false },
    { id: 'aceite', label: 'Aceite', start: 150, end: 150, type: 'enum', enum: ['A', 'N'], required: false },
    { id: 'data_emissao', label: 'Data emissão', start: 151, end: 156, type: 'date', format: 'DDMMAA', required: false },
    { id: 'instrucoes', label: 'Instruções codificadas', start: 157, end: 160, type: 'numeric', required: false },
    { id: 'mora', label: 'Mora/dia', start: 161, end: 173, type: 'money', required: false },
    { id: 'data_desconto', label: 'Data desconto', start: 174, end: 179, type: 'date', format: 'DDMMAA', required: false },
    { id: 'valor_desconto', label: 'Valor desconto', start: 180, end: 192, type: 'money', required: false },
    { id: 'iof', label: 'IOF', start: 193, end: 205, type: 'money', required: false },
    { id: 'abatimento', label: 'Abatimento', start: 206, end: 218, type: 'money', required: false },
    { id: 'tipo_inscricao', label: 'Tipo inscrição sacado', start: 219, end: 220, type: 'enum', enum: ['01', '02'] },
    { id: 'cpf_cnpj', label: 'CPF/CNPJ sacado', start: 221, end: 234, type: 'numeric', issueCode: 'F400_DET_CPF' },
    { id: 'nome_sacado', label: 'Nome sacado', start: 235, end: 274, type: 'alpha', issueCode: 'F400_DET_NOME' },
    { id: 'endereco', label: 'Endereço sacado', start: 275, end: 314, type: 'alpha', required: false },
    { id: 'bairro', label: 'Bairro', start: 315, end: 326, type: 'alpha', required: false },
    { id: 'cep', label: 'CEP', start: 327, end: 334, type: 'numeric', issueCode: 'F400_DET_CEP' },
    { id: 'cidade', label: 'Cidade', start: 335, end: 349, type: 'alpha', required: false },
    { id: 'uf', label: 'UF', start: 350, end: 351, type: 'alpha', required: false },
    { id: 'mensagem', label: 'Mensagem/observações', start: 352, end: 391, type: 'alpha', required: false },
    { id: 'prazo_protesto', label: 'Prazo protesto', start: 392, end: 393, type: 'numeric', required: false },
    { id: 'pagamento_parcial', label: 'Pagamento parcial', start: 394, end: 394, type: 'alphanumeric', required: false },
    { id: 'sequencial', label: 'Sequencial', start: 395, end: 400, type: 'numeric', pad: 'numeric', issueCode: 'F400_DET_SEQ' },
  ],
}
