import type { RecordSpec } from '../../../../types'

/** Detalhe CNAB400 Sicoob — ACBrBancoSicoob.GerarRegistroTransacao400 */
export const SICOOB_C400_DETALHE_1: RecordSpec = {
  id: 'cobBancoSicoob-c400-detalhe-1',
  layout: 'c400',
  recordType: '1',
  label: 'Detalhe Sicoob CNAB400',
  lineLength: 400,
  bankId: 'cobBancoSicoob',
  acbrRef: 'ACBrBancoSicoob.pas:GerarRegistroTransacao400',
  fields: [
    { id: 'tipo_registro', label: 'Tipo registro', start: 1, end: 1, type: 'enum', enum: ['1'], issueCode: 'F400_DET_TIPO' },
    { id: 'tipo_inscricao_cedente', label: 'Tipo inscrição cedente', start: 2, end: 3, type: 'enum', enum: ['01', '02'] },
    { id: 'cnpj_cedente', label: 'CNPJ/CPF cedente', start: 4, end: 17, type: 'numeric' },
    { id: 'agencia', label: 'Agência', start: 18, end: 21, type: 'numeric' },
    { id: 'dv_agencia', label: 'DV agência', start: 22, end: 22, type: 'alphanumeric', required: false },
    { id: 'conta', label: 'Conta', start: 23, end: 30, type: 'numeric' },
    { id: 'dv_conta', label: 'DV conta', start: 31, end: 31, type: 'alphanumeric', required: false },
    { id: 'convenio', label: 'Convênio', start: 32, end: 37, type: 'numeric', required: false },
    { id: 'seu_numero', label: 'Seu número', start: 38, end: 62, type: 'alphanumeric', required: false },
    { id: 'nosso_numero', label: 'Nosso número', start: 63, end: 74, type: 'numeric', issueCode: 'F400_SCO_NOSSO' },
    { id: 'modalidade', label: 'Modalidade', start: 107, end: 108, type: 'numeric', required: false },
    {
      id: 'ocorrencia',
      label: 'Ocorrência',
      start: 109,
      end: 110,
      type: 'enum',
      enumRef: 'sicoob-remessa-400',
      issueCode: 'F400_SCO_OCORR',
    },
    { id: 'numero_documento', label: 'Número documento', start: 111, end: 120, type: 'alphanumeric', issueCode: 'F400_DET_DOC' },
    { id: 'vencimento', label: 'Vencimento', start: 121, end: 126, type: 'date', format: 'DDMMAA', issueCode: 'F400_DET_VENC' },
    { id: 'valor', label: 'Valor título', start: 127, end: 139, type: 'money', issueCode: 'F400_DET_VALOR' },
    { id: 'codigo_banco', label: 'Código banco', start: 140, end: 142, type: 'numeric' },
    { id: 'agencia_cobradora', label: 'Agência cobradora', start: 143, end: 146, type: 'numeric', required: false },
    { id: 'dv_ag_cobradora', label: 'DV ag. cobradora', start: 147, end: 147, type: 'alphanumeric', required: false },
    { id: 'especie', label: 'Espécie', start: 148, end: 149, type: 'alphanumeric', required: false },
    { id: 'aceite', label: 'Aceite', start: 150, end: 150, type: 'enum', enum: ['0', '1'], required: false },
    { id: 'tipo_inscricao', label: 'Tipo inscrição sacado', start: 219, end: 220, type: 'enum', enum: ['01', '02', '99'] },
    { id: 'cpf_cnpj', label: 'CPF/CNPJ sacado', start: 221, end: 234, type: 'numeric', issueCode: 'F400_DET_CPF' },
    { id: 'nome_sacado', label: 'Nome sacado', start: 235, end: 274, type: 'alpha', issueCode: 'F400_DET_NOME' },
    { id: 'sequencial', label: 'Sequencial', start: 393, end: 398, type: 'numeric', pad: 'numeric', issueCode: 'F400_DET_SEQ' },
  ],
}
