import type { RecordSpec } from '../../../../types'

/** Detalhe CNAB400 Caixa — ACBrBancoCaixa.GerarRegistroTransacao400 */
export const CAIXA_C400_DETALHE_1: RecordSpec = {
  id: 'cobCaixaEconomica-c400-detalhe-1',
  layout: 'c400',
  recordType: '1',
  label: 'Detalhe Caixa CNAB400',
  lineLength: 400,
  bankId: 'cobCaixaEconomica',
  acbrRef: 'ACBrBancoCaixa.pas:GerarRegistroTransacao400',
  fields: [
    { id: 'tipo_registro', label: 'Tipo registro', start: 1, end: 1, type: 'enum', enum: ['1'], issueCode: 'F400_DET_TIPO' },
    { id: 'tipo_inscricao_cedente', label: 'Tipo inscrição cedente', start: 2, end: 3, type: 'enum', enum: ['01', '02'] },
    { id: 'cnpj_cedente', label: 'CNPJ/CPF cedente', start: 4, end: 17, type: 'numeric' },
    { id: 'agencia', label: 'Agência', start: 18, end: 21, type: 'numeric', issueCode: 'F400_CX_AG' },
    { id: 'codigo_cedente', label: 'Código cedente', start: 22, end: 27, type: 'alphanumeric', issueCode: 'F400_CX_CED' },
    { id: 'emissao_distribuicao', label: 'Emissão/distribuição', start: 28, end: 29, type: 'alphanumeric', required: false },
    { id: 'comissao_permanencia', label: 'Comissão permanência', start: 30, end: 31, type: 'enum', enum: ['00'], required: false },
    { id: 'seu_numero', label: 'Seu número', start: 32, end: 56, type: 'alphanumeric', required: false },
    { id: 'modalidade', label: 'Modalidade carteira', start: 57, end: 58, type: 'numeric', required: false },
    { id: 'nosso_numero', label: 'Nosso número', start: 59, end: 73, type: 'numeric', issueCode: 'F400_CX_NOSSO' },
    { id: 'brancos_74', label: 'Brancos', start: 74, end: 75, type: 'filler', required: false },
    { id: 'pagamento_parcial', label: 'Pagamento parcial', start: 76, end: 76, type: 'alphanumeric', required: false },
    { id: 'codigo_juros', label: 'Código juros', start: 77, end: 77, type: 'enum', enum: ['1', '3', '5', '6', '8'], required: false },
    { id: 'data_juros', label: 'Data início juros', start: 78, end: 83, type: 'date', format: 'DDMMAA', required: false },
    { id: 'codigo_desconto', label: 'Código desconto', start: 84, end: 84, type: 'enum', enum: ['0', '1', '2', '3', '4', '5', '6'], required: false },
    { id: 'brancos_85', label: 'Brancos', start: 85, end: 106, type: 'filler', required: false },
    { id: 'carteira', label: 'Carteira', start: 107, end: 108, type: 'enum', enum: ['01'], issueCode: 'F400_CX_CART' },
    {
      id: 'ocorrencia',
      label: 'Código ocorrência',
      start: 109,
      end: 110,
      type: 'enum',
      enumRef: 'caixa-remessa-400',
      issueCode: 'F400_CX_OCORR',
    },
    { id: 'numero_documento', label: 'Número documento', start: 111, end: 120, type: 'alphanumeric', issueCode: 'F400_DET_DOC' },
    { id: 'vencimento', label: 'Vencimento', start: 121, end: 126, type: 'date', format: 'DDMMAA', issueCode: 'F400_DET_VENC' },
    { id: 'valor', label: 'Valor título', start: 127, end: 139, type: 'money', issueCode: 'F400_DET_VALOR' },
    { id: 'codigo_banco', label: 'Código banco', start: 140, end: 142, type: 'numeric' },
    { id: 'agencia_cobradora', label: 'Agência cobradora', start: 143, end: 147, type: 'numeric', required: false },
    { id: 'especie', label: 'Espécie documento', start: 148, end: 149, type: 'numeric', required: false },
    { id: 'aceite', label: 'Aceite', start: 150, end: 150, type: 'enum', enum: ['A', 'N'], required: false },
    { id: 'data_emissao', label: 'Data emissão', start: 151, end: 156, type: 'date', format: 'DDMMAA', required: false },
    { id: 'instrucao1', label: '1ª instrução', start: 157, end: 158, type: 'numeric', required: false },
    { id: 'instrucao2', label: '2ª instrução', start: 159, end: 160, type: 'numeric', required: false },
    { id: 'mora', label: 'Mora/dia', start: 161, end: 173, type: 'money', required: false },
    { id: 'data_desconto', label: 'Data desconto', start: 174, end: 179, type: 'date', format: 'DDMMAA', required: false },
    { id: 'valor_desconto', label: 'Valor desconto', start: 180, end: 192, type: 'money', required: false },
    { id: 'iof', label: 'IOF', start: 193, end: 205, type: 'money', required: false },
    { id: 'abatimento', label: 'Abatimento', start: 206, end: 218, type: 'money', required: false },
    { id: 'tipo_inscricao', label: 'Tipo inscrição sacado', start: 219, end: 220, type: 'enum', enum: ['01', '02'] },
    { id: 'cpf_cnpj', label: 'CPF/CNPJ sacado', start: 221, end: 234, type: 'numeric', issueCode: 'F400_DET_CPF' },
    { id: 'nome_sacado', label: 'Nome sacado', start: 235, end: 274, type: 'alpha', issueCode: 'F400_DET_NOME' },
    { id: 'endereco', label: 'Endereço sacado', start: 275, end: 314, type: 'alpha', required: false },
    { id: 'bairro', label: 'Bairro', start: 315, end: 326, type: 'alpha', required: false },
    { id: 'cep', label: 'CEP', start: 327, end: 334, type: 'numeric', required: false },
    { id: 'cidade', label: 'Cidade', start: 335, end: 349, type: 'alpha', required: false },
    { id: 'uf', label: 'UF', start: 350, end: 351, type: 'alpha', required: false },
    { id: 'data_multa', label: 'Data multa', start: 352, end: 357, type: 'date', format: 'DDMMAA', required: false },
    { id: 'valor_multa', label: 'Valor multa', start: 358, end: 367, type: 'numeric', required: false },
    { id: 'avalista', label: 'Sacador avalista', start: 368, end: 389, type: 'alpha', required: false },
    { id: 'instrucao3', label: '3ª instrução', start: 390, end: 391, type: 'numeric', required: false },
    { id: 'prazo_protesto', label: 'Prazo protesto/devolução', start: 392, end: 393, type: 'alphanumeric', required: false },
    { id: 'codigo_moeda', label: 'Código moeda', start: 394, end: 394, type: 'enum', enum: ['1'], required: false },
    { id: 'sequencial', label: 'Sequencial', start: 395, end: 400, type: 'numeric', pad: 'numeric', issueCode: 'F400_DET_SEQ' },
  ],
}
