import { SANTANDER_C240_HEADER_ARQ, SANTANDER_C240_HEADER_LOTE } from './header'
import { SANTANDER_C240_SEGMENTO_P } from './segmento-p'
import { SANTANDER_C240_SEGMENTO_Q } from './segmento-q'

export const SANTANDER_C240_SPECS = [
  SANTANDER_C240_HEADER_ARQ,
  SANTANDER_C240_HEADER_LOTE,
  SANTANDER_C240_SEGMENTO_P,
  SANTANDER_C240_SEGMENTO_Q,
]
