import type { RecordSpec } from '../../../../types'

/** Segmento P CNAB240 Santander — ACBrBancoSantander.GerarRegistroTransacao240 */
export const SANTANDER_C240_SEGMENTO_P: RecordSpec = {
  id: 'cobSantander-c240-segmento-p',
  layout: 'c240',
  recordType: '3P',
  label: 'Segmento P Santander',
  lineLength: 240,
  bankId: 'cobSantander',
  acbrRef: 'ACBrBancoSantander.pas:GerarRegistroTransacao240',
  fields: [
    { id: 'codigo_banco', label: 'Código banco', start: 1, end: 3, type: 'numeric' },
    { id: 'lote', label: 'Lote', start: 4, end: 7, type: 'numeric' },
    { id: 'tipo_registro', label: 'Tipo registro', start: 8, end: 8, type: 'enum', enum: ['3'] },
    { id: 'sequencial', label: 'Sequencial lote', start: 9, end: 13, type: 'numeric' },
    { id: 'segmento', label: 'Segmento', start: 14, end: 14, type: 'enum', enum: ['P'] },
    { id: 'uso_banco', label: 'Uso banco', start: 15, end: 15, type: 'filler', required: false },
    {
      id: 'codigo_movimento',
      label: 'Código movimento',
      start: 16,
      end: 17,
      type: 'enum',
      enumRef: 'santander-remessa-240',
      issueCode: 'F240_SANT_MOV',
    },
    { id: 'agencia', label: 'Agência', start: 18, end: 21, type: 'numeric' },
    { id: 'dv_agencia', label: 'DV agência', start: 22, end: 22, type: 'alphanumeric', required: false },
    { id: 'conta', label: 'Conta', start: 23, end: 31, type: 'numeric' },
    { id: 'dv_conta', label: 'DV conta', start: 32, end: 32, type: 'alphanumeric', required: false },
    { id: 'conta_cobranca', label: 'Conta cobrança', start: 33, end: 41, type: 'numeric', required: false },
    { id: 'dv_conta_cob', label: 'DV conta cobrança', start: 42, end: 42, type: 'alphanumeric', required: false },
    { id: 'uso_banco2', label: 'Uso banco', start: 43, end: 44, type: 'filler', required: false },
    { id: 'nosso_numero', label: 'Nosso número', start: 45, end: 57, type: 'numeric', issueCode: 'F240_SANT_NOSSO' },
    { id: 'tipo_cobranca', label: 'Tipo cobrança', start: 58, end: 58, type: 'alphanumeric', required: false },
    { id: 'tipo_carteira', label: 'Forma cadastramento', start: 59, end: 59, type: 'enum', enum: ['1', '2'], required: false },
    { id: 'tipo_documento', label: 'Tipo documento', start: 60, end: 60, type: 'alphanumeric', required: false },
    { id: 'uso_banco3', label: 'Uso banco', start: 61, end: 62, type: 'filler', required: false },
    { id: 'numero_documento', label: 'Nº documento', start: 63, end: 77, type: 'alphanumeric' },
    { id: 'vencimento', label: 'Vencimento', start: 78, end: 85, type: 'date', format: 'DDMMAAAA', issueCode: 'F240_SEGP_VENC' },
    { id: 'valor', label: 'Valor nominal', start: 86, end: 100, type: 'money', issueCode: 'F240_SEGP_VALOR' },
    { id: 'agencia_cobradora', label: 'Agência cobradora', start: 101, end: 104, type: 'numeric', required: false },
    { id: 'dv_ag_cobradora', label: 'DV ag. cobradora', start: 105, end: 105, type: 'alphanumeric', required: false },
    { id: 'uso_banco4', label: 'Uso banco', start: 106, end: 106, type: 'filler', required: false },
    { id: 'especie', label: 'Espécie documento', start: 107, end: 108, type: 'numeric', required: false },
    { id: 'aceite', label: 'Aceite', start: 109, end: 109, type: 'enum', enum: ['A', 'N'], required: false },
    { id: 'data_emissao', label: 'Data emissão', start: 110, end: 117, type: 'date', format: 'DDMMAAAA', required: false },
    { id: 'codigo_juros', label: 'Código juros', start: 118, end: 118, type: 'enum', enum: ['0', '1', '2', '3'], required: false },
    { id: 'data_juros', label: 'Data juros', start: 119, end: 126, type: 'date', format: 'DDMMAAAA', required: false },
    { id: 'valor_juros', label: 'Valor juros', start: 127, end: 141, type: 'money', required: false },
    { id: 'codigo_desconto', label: 'Código desconto', start: 142, end: 142, type: 'enum', enum: ['0', '1', '2', '3', '4'], required: false },
    { id: 'data_desconto', label: 'Data desconto', start: 143, end: 150, type: 'date', format: 'DDMMAAAA', required: false },
    { id: 'valor_desconto', label: 'Valor desconto', start: 151, end: 165, type: 'money', required: false },
    { id: 'iof', label: 'IOF', start: 166, end: 180, type: 'money', required: false },
    { id: 'abatimento', label: 'Abatimento', start: 181, end: 195, type: 'money', required: false },
    { id: 'seu_numero', label: 'Seu número', start: 196, end: 220, type: 'alphanumeric', required: false },
    { id: 'instrucoes_protesto', label: 'Instruções protesto', start: 221, end: 224, type: 'alphanumeric', required: false },
    { id: 'uso_banco5', label: 'Uso banco', start: 225, end: 225, type: 'filler', required: false },
    { id: 'dias_baixa', label: 'Dias baixa', start: 226, end: 227, type: 'numeric', required: false },
    { id: 'codigo_moeda', label: 'Código moeda', start: 228, end: 229, type: 'enum', enum: ['00'], required: false },
    { id: 'resto', label: 'Uso banco', start: 230, end: 240, type: 'filler', required: false },
  ],
}
