import type { RecordSpec } from '../../../../types'

/** Segmento P CNAB240 Itaú — ACBrBancoItau.GerarRegistroTransacao240 */
export const ITAU_C240_SEGMENTO_P: RecordSpec = {
  id: 'cobItau-c240-segmento-p',
  layout: 'c240',
  recordType: '3P',
  label: 'Segmento P Itaú',
  lineLength: 240,
  bankId: 'cobItau',
  acbrRef: 'ACBrBancoItau.pas:GerarRegistroTransacao240',
  fields: [
    { id: 'codigo_banco', label: 'Código banco', start: 1, end: 3, type: 'numeric' },
    { id: 'lote', label: 'Lote', start: 4, end: 7, type: 'numeric' },
    { id: 'tipo_registro', label: 'Tipo registro', start: 8, end: 8, type: 'enum', enum: ['3'] },
    { id: 'sequencial', label: 'Sequencial lote', start: 9, end: 13, type: 'numeric' },
    { id: 'segmento', label: 'Segmento', start: 14, end: 14, type: 'enum', enum: ['P'] },
    { id: 'uso_febraban', label: 'Uso FEBRABAN', start: 15, end: 15, type: 'filler', required: false },
    {
      id: 'codigo_movimento',
      label: 'Código movimento',
      start: 16,
      end: 17,
      type: 'enum',
      enumRef: 'itau-remessa-240',
      issueCode: 'F240_ITAU_MOV',
    },
    { id: 'complemento_18', label: 'Complemento', start: 18, end: 18, type: 'enum', enum: ['0'], required: false },
    { id: 'agencia', label: 'Agência', start: 19, end: 22, type: 'numeric' },
    { id: 'dv_agencia', label: 'DV agência', start: 23, end: 23, type: 'alphanumeric', required: false },
    { id: 'complemento_conta', label: 'Complemento conta', start: 24, end: 30, type: 'alphanumeric', required: false },
    { id: 'conta', label: 'Conta', start: 31, end: 35, type: 'numeric' },
    { id: 'dv_conta_sep', label: 'Separador', start: 36, end: 36, type: 'filler', required: false },
    { id: 'dv_conta', label: 'DV conta', start: 37, end: 37, type: 'alphanumeric', required: false },
    { id: 'carteira', label: 'Carteira', start: 38, end: 40, type: 'alphanumeric' },
    { id: 'nosso_numero', label: 'Nosso número', start: 41, end: 48, type: 'numeric', issueCode: 'F240_ITAU_NOSSO' },
    { id: 'dv_nosso_numero', label: 'DV nosso número', start: 49, end: 49, type: 'alphanumeric', required: false },
    { id: 'brancos_50', label: 'Brancos', start: 50, end: 57, type: 'filler', required: false },
    { id: 'complemento_58', label: 'Complemento', start: 58, end: 62, type: 'alphanumeric', required: false },
    { id: 'numero_documento', label: 'Nº documento', start: 63, end: 72, type: 'alphanumeric' },
    { id: 'brancos_73', label: 'Brancos', start: 73, end: 77, type: 'filler', required: false },
    { id: 'vencimento', label: 'Vencimento', start: 78, end: 85, type: 'date', format: 'DDMMAAAA', issueCode: 'F240_SEGP_VENC' },
    { id: 'valor', label: 'Valor nominal', start: 86, end: 100, type: 'money', issueCode: 'F240_SEGP_VALOR' },
    { id: 'agencia_cobradora', label: 'Agência cobradora', start: 101, end: 105, type: 'numeric', required: false },
    { id: 'dv_ag_cobradora', label: 'DV agência cobradora', start: 106, end: 106, type: 'alphanumeric', required: false },
    { id: 'especie', label: 'Espécie documento', start: 107, end: 108, type: 'alphanumeric', required: false },
    { id: 'aceite', label: 'Aceite', start: 109, end: 109, type: 'enum', enum: ['N', 'S'], required: false },
    { id: 'data_emissao', label: 'Data emissão', start: 110, end: 117, type: 'date', format: 'DDMMAAAA', required: false },
    { id: 'zeros_118', label: 'Zeros', start: 118, end: 118, type: 'enum', enum: ['0'], required: false },
    { id: 'data_mora', label: 'Data mora', start: 119, end: 126, type: 'date', format: 'DDMMAAAA', required: false },
    { id: 'valor_mora', label: 'Valor mora/dia', start: 127, end: 141, type: 'money', required: false },
    { id: 'zeros_142', label: 'Zeros', start: 142, end: 142, type: 'enum', enum: ['0'], required: false },
    { id: 'data_desconto', label: 'Data desconto', start: 143, end: 150, type: 'date', format: 'DDMMAAAA', required: false },
    { id: 'valor_desconto', label: 'Valor desconto', start: 151, end: 165, type: 'money', required: false },
    { id: 'iof', label: 'IOF', start: 166, end: 180, type: 'money', required: false },
    { id: 'abatimento', label: 'Abatimento', start: 181, end: 195, type: 'money', required: false },
    { id: 'seu_numero', label: 'Seu número', start: 196, end: 220, type: 'alphanumeric', required: false },
    { id: 'codigo_protesto', label: 'Código protesto', start: 221, end: 221, type: 'alphanumeric', required: false },
    { id: 'prazo_protesto', label: 'Prazo protesto', start: 222, end: 223, type: 'numeric', required: false },
    { id: 'codigo_baixa', label: 'Código baixa', start: 224, end: 224, type: 'alphanumeric', required: false },
    { id: 'dias_baixa', label: 'Dias baixa', start: 225, end: 226, type: 'numeric', required: false },
    { id: 'resto', label: 'Complemento', start: 227, end: 240, type: 'filler', required: false },
  ],
}
