import type { RecordSpec } from '../../../../types'

/** Header arquivo CNAB240 BB — ACBrBancoBrasil.GerarRegistroHeader240 */
export const BB_C240_HEADER_ARQ: RecordSpec = {
  id: 'cobBancoDoBrasil-c240-header-arquivo-0000',
  layout: 'c240',
  recordType: '0000-0',
  label: 'Header arquivo BB CNAB240',
  lineLength: 240,
  bankId: 'cobBancoDoBrasil',
  acbrRef: 'ACBrBancoBrasil.pas:GerarRegistroHeader240',
  fields: [
    { id: 'codigo_banco', label: 'Código banco', start: 1, end: 3, type: 'numeric', issueCode: 'F240_HDR_BANCO' },
    { id: 'lote', label: 'Lote', start: 4, end: 7, type: 'enum', enum: ['0000'] },
    { id: 'tipo_registro', label: 'Tipo registro', start: 8, end: 8, type: 'enum', enum: ['0'] },
    { id: 'uso_febraban', label: 'Uso FEBRABAN', start: 9, end: 17, type: 'filler', required: false },
    { id: 'tipo_inscricao', label: 'Tipo inscrição', start: 18, end: 18, type: 'enum', enum: ['1', '2'] },
    { id: 'cnpj_cpf', label: 'CNPJ/CPF', start: 19, end: 32, type: 'numeric' },
    { id: 'convenio', label: 'Convênio', start: 33, end: 41, type: 'numeric', issueCode: 'F240_BB_CONV' },
    { id: 'tipo_cedente', label: 'Tipo cedente', start: 42, end: 45, type: 'enum', enum: ['0014'] },
    { id: 'carteira', label: 'Carteira', start: 46, end: 47, type: 'numeric' },
    { id: 'modalidade', label: 'Variação carteira', start: 48, end: 50, type: 'numeric', required: false },
    { id: 'brancos_51', label: 'Brancos', start: 51, end: 52, type: 'filler', required: false },
    { id: 'agencia', label: 'Agência', start: 53, end: 57, type: 'numeric' },
    { id: 'dv_agencia', label: 'DV agência', start: 58, end: 58, type: 'alphanumeric', required: false },
    { id: 'conta', label: 'Conta', start: 59, end: 70, type: 'numeric' },
    { id: 'dv_conta', label: 'DV conta', start: 71, end: 71, type: 'alphanumeric', required: false },
    { id: 'dv_ag_conta', label: 'DV ag/conta', start: 72, end: 72, type: 'alphanumeric', required: false },
    { id: 'nome_empresa', label: 'Nome empresa', start: 73, end: 102, type: 'alpha' },
    { id: 'nome_banco', label: 'Nome banco', start: 103, end: 132, type: 'alpha' },
    { id: 'uso_febraban2', label: 'Uso FEBRABAN', start: 133, end: 142, type: 'filler', required: false },
    { id: 'remessa_retorno', label: 'Remessa/Retorno', start: 143, end: 143, type: 'enum', enum: ['1'], issueCode: 'F240_HDR_REM_RET' },
    { id: 'data_geracao', label: 'Data geração', start: 144, end: 151, type: 'date', format: 'DDMMAAAA' },
    { id: 'hora_geracao', label: 'Hora geração', start: 152, end: 157, type: 'time' },
    { id: 'numero_arquivo', label: 'Nº sequencial arquivo', start: 158, end: 163, type: 'numeric' },
    { id: 'versao_layout', label: 'Versão layout', start: 164, end: 166, type: 'numeric' },
    { id: 'densidade', label: 'Densidade', start: 167, end: 171, type: 'numeric', required: false },
    { id: 'uso_banco', label: 'Uso banco', start: 172, end: 191, type: 'filler', required: false },
    { id: 'uso_empresa', label: 'Uso empresa', start: 192, end: 211, type: 'filler', required: false },
    { id: 'brancos_212', label: 'Brancos', start: 212, end: 222, type: 'filler', required: false },
    { id: 'ident_csp', label: 'Identificador CSP', start: 223, end: 225, type: 'alpha', required: false },
    { id: 'uso_vans', label: 'Uso VANs', start: 226, end: 228, type: 'alphanumeric', required: false },
    { id: 'resto', label: 'Complemento', start: 229, end: 240, type: 'filler', required: false },
  ],
}

/** Header lote CNAB240 BB */
export const BB_C240_HEADER_LOTE: RecordSpec = {
  id: 'cobBancoDoBrasil-c240-header-lote-0001',
  layout: 'c240',
  recordType: '0001-1',
  label: 'Header lote BB CNAB240',
  lineLength: 240,
  bankId: 'cobBancoDoBrasil',
  acbrRef: 'ACBrBancoBrasil.pas:GerarRegistroHeader240',
  fields: [
    { id: 'codigo_banco', label: 'Código banco', start: 1, end: 3, type: 'numeric' },
    { id: 'lote', label: 'Lote', start: 4, end: 7, type: 'enum', enum: ['0001'] },
    { id: 'tipo_registro', label: 'Tipo registro', start: 8, end: 8, type: 'enum', enum: ['1'] },
    { id: 'operacao', label: 'Operação', start: 9, end: 9, type: 'enum', enum: ['R'], issueCode: 'F240_LOTE_OP' },
    { id: 'servico', label: 'Serviço', start: 10, end: 11, type: 'enum', enum: ['01'], issueCode: 'F240_LOTE_SERV' },
    { id: 'uso_febraban', label: 'Uso FEBRABAN', start: 12, end: 13, type: 'filler', required: false },
    { id: 'versao_lote', label: 'Versão layout lote', start: 14, end: 16, type: 'numeric' },
    { id: 'uso_febraban2', label: 'Uso FEBRABAN', start: 17, end: 17, type: 'filler', required: false },
    { id: 'tipo_inscricao', label: 'Tipo inscrição', start: 18, end: 18, type: 'enum', enum: ['1', '2'] },
    { id: 'cnpj_cpf', label: 'CNPJ/CPF', start: 19, end: 33, type: 'numeric' },
    { id: 'convenio', label: 'Convênio', start: 34, end: 42, type: 'numeric', issueCode: 'F240_BB_CONV' },
    { id: 'tipo_cedente', label: 'Tipo cedente', start: 43, end: 46, type: 'enum', enum: ['0014'] },
    { id: 'carteira', label: 'Carteira', start: 47, end: 48, type: 'numeric' },
    { id: 'modalidade', label: 'Variação carteira', start: 49, end: 51, type: 'numeric', required: false },
    { id: 'homologacao', label: 'Homologação', start: 52, end: 53, type: 'alphanumeric', required: false },
    { id: 'agencia', label: 'Agência', start: 54, end: 58, type: 'numeric' },
    { id: 'dv_agencia', label: 'DV agência', start: 59, end: 59, type: 'alphanumeric', required: false },
    { id: 'conta', label: 'Conta', start: 60, end: 71, type: 'numeric' },
    { id: 'dv_conta', label: 'DV conta', start: 72, end: 72, type: 'alphanumeric', required: false },
    { id: 'dv_ag_conta', label: 'DV ag/conta', start: 73, end: 73, type: 'alphanumeric', required: false },
    { id: 'nome_cedente', label: 'Nome cedente', start: 74, end: 103, type: 'alpha' },
    { id: 'mensagem1', label: 'Mensagem 1', start: 104, end: 143, type: 'alpha', required: false },
    { id: 'mensagem2', label: 'Mensagem 2', start: 144, end: 183, type: 'alpha', required: false },
    { id: 'numero_remessa', label: 'Nº remessa', start: 184, end: 191, type: 'numeric' },
    { id: 'data_gravacao', label: 'Data gravação', start: 192, end: 199, type: 'date', format: 'DDMMAAAA' },
    { id: 'data_credito', label: 'Data crédito', start: 200, end: 207, type: 'date', format: 'DDMMAAAA', required: false },
    { id: 'uso_exclusivo', label: 'Uso exclusivo', start: 208, end: 240, type: 'filler', required: false },
  ],
}
