import type { RecordSpec } from '../../../types'

/** Header arquivo CNAB240 retorno — pos 143 = 2 */
export const FEBRABAN_RETORNO_C240_HEADER_ARQ: RecordSpec = {
  id: 'febraban-retorno-c240-header-arquivo-0000',
  layout: 'c240',
  kind: 'retorno',
  recordType: '0000-0',
  label: 'Header arquivo CNAB240 Retorno',
  lineLength: 240,
  acbrRef: 'ACBrBoleto.pas:TACBrBoleto.LerRetorno (pos 143=2)',
  fields: [
    { id: 'codigo_banco', label: 'Código banco', start: 1, end: 3, type: 'numeric', issueCode: 'F240_HDR_BANCO' },
    { id: 'lote', label: 'Lote', start: 4, end: 7, type: 'enum', enum: ['0000'] },
    { id: 'tipo_registro', label: 'Tipo registro', start: 8, end: 8, type: 'enum', enum: ['0'] },
    { id: 'uso_febraban', label: 'Uso FEBRABAN', start: 9, end: 17, type: 'filler', required: false },
    { id: 'tipo_inscricao', label: 'Tipo inscrição', start: 18, end: 18, type: 'enum', enum: ['1', '2'], required: false },
    { id: 'cnpj_cpf', label: 'CNPJ/CPF', start: 19, end: 32, type: 'numeric', required: false },
    { id: 'convenio', label: 'Convênio', start: 33, end: 52, type: 'alphanumeric', bankOverride: true, required: false },
    { id: 'agencia', label: 'Agência', start: 53, end: 57, type: 'numeric', required: false },
    { id: 'dv_agencia', label: 'DV agência', start: 58, end: 58, type: 'alphanumeric', required: false },
    { id: 'conta', label: 'Conta', start: 59, end: 70, type: 'numeric', required: false },
    { id: 'dv_conta', label: 'DV conta', start: 71, end: 71, type: 'alphanumeric', required: false },
    { id: 'dv_ag_conta', label: 'DV ag/conta', start: 72, end: 72, type: 'alphanumeric', required: false },
    { id: 'nome_empresa', label: 'Nome empresa', start: 73, end: 102, type: 'alpha', required: false },
    { id: 'nome_banco', label: 'Nome banco', start: 103, end: 132, type: 'alpha', required: false },
    { id: 'uso_febraban2', label: 'Uso FEBRABAN', start: 133, end: 142, type: 'filler', required: false },
    {
      id: 'remessa_retorno',
      label: 'Remessa/Retorno',
      start: 143,
      end: 143,
      type: 'enum',
      enum: ['2'],
      issueCode: 'F240_HDR_REM_RET',
    },
    { id: 'data_geracao', label: 'Data geração', start: 144, end: 151, type: 'date', format: 'DDMMAAAA', required: false },
    { id: 'hora_geracao', label: 'Hora geração', start: 152, end: 157, type: 'time', required: false },
    { id: 'numero_arquivo', label: 'Nº sequencial arquivo', start: 158, end: 163, type: 'numeric', required: false },
    { id: 'versao_layout', label: 'Versão layout', start: 164, end: 166, type: 'numeric', required: false },
    { id: 'densidade', label: 'Densidade', start: 167, end: 171, type: 'numeric', required: false },
    { id: 'uso_exclusivo', label: 'Uso exclusivo', start: 172, end: 240, type: 'filler', required: false },
  ],
}

export const FEBRABAN_RETORNO_C240_HEADER_LOTE: RecordSpec = {
  id: 'febraban-retorno-c240-header-lote-0001',
  layout: 'c240',
  kind: 'retorno',
  recordType: '0001-1',
  label: 'Header lote CNAB240 Retorno',
  lineLength: 240,
  fields: [
    { id: 'codigo_banco', label: 'Código banco', start: 1, end: 3, type: 'numeric' },
    { id: 'lote', label: 'Lote', start: 4, end: 7, type: 'numeric' },
    { id: 'tipo_registro', label: 'Tipo registro', start: 8, end: 8, type: 'enum', enum: ['1'] },
    {
      id: 'operacao',
      label: 'Operação',
      start: 9,
      end: 9,
      type: 'enum',
      enum: ['T'],
      issueCode: 'F240_LOTE_OP',
    },
    {
      id: 'servico',
      label: 'Serviço',
      start: 10,
      end: 11,
      type: 'enum',
      enum: ['01'],
      issueCode: 'F240_LOTE_SERV',
      required: false,
    },
    { id: 'uso_febraban', label: 'Uso FEBRABAN', start: 12, end: 13, type: 'filler', required: false },
    { id: 'versao_lote', label: 'Versão layout lote', start: 14, end: 16, type: 'numeric', required: false },
    { id: 'resto', label: 'Demais campos lote', start: 17, end: 240, type: 'filler', required: false },
  ],
}

/** Segmento T — título + movimento retorno (ACBr LerRetorno240) */
export const FEBRABAN_RETORNO_C240_SEGMENTO_T: RecordSpec = {
  id: 'febraban-retorno-c240-segmento-t',
  layout: 'c240',
  kind: 'retorno',
  recordType: '3T',
  label: 'Segmento T (retorno)',
  lineLength: 240,
  acbrRef: 'ACBrBoleto.pas:TACBrBancoClass.LerRetorno240 (seg T)',
  fields: [
    { id: 'codigo_banco', label: 'Código banco', start: 1, end: 3, type: 'numeric' },
    { id: 'lote', label: 'Lote', start: 4, end: 7, type: 'numeric' },
    { id: 'tipo_registro', label: 'Tipo registro', start: 8, end: 8, type: 'enum', enum: ['3'] },
    { id: 'sequencial', label: 'Sequencial lote', start: 9, end: 13, type: 'numeric' },
    { id: 'segmento', label: 'Segmento', start: 14, end: 14, type: 'enum', enum: ['T'] },
    { id: 'uso_febraban', label: 'Uso FEBRABAN', start: 15, end: 15, type: 'filler', required: false },
    {
      id: 'codigo_movimento',
      label: 'Código movimento',
      start: 16,
      end: 17,
      type: 'enum',
      enumRef: 'febraban-retorno-240',
      issueCode: 'F240_SEGT_MOV',
    },
    { id: 'agencia', label: 'Agência', start: 18, end: 22, type: 'numeric', required: false },
    { id: 'dv_agencia', label: 'DV agência', start: 23, end: 23, type: 'alphanumeric', required: false },
    { id: 'conta', label: 'Conta', start: 24, end: 35, type: 'numeric', required: false },
    { id: 'dv_conta', label: 'DV conta', start: 36, end: 36, type: 'alphanumeric', required: false },
    { id: 'dv_ag_conta', label: 'DV ag/conta', start: 37, end: 37, type: 'filler', required: false },
    { id: 'nosso_numero', label: 'Nosso número', start: 38, end: 57, type: 'alphanumeric', required: false, issueCode: 'F240_SEGT_NOSSO' },
    { id: 'carteira', label: 'Carteira', start: 58, end: 58, type: 'alphanumeric', required: false },
    { id: 'numero_documento', label: 'Nº documento', start: 59, end: 73, type: 'alphanumeric', required: false },
    {
      id: 'vencimento',
      label: 'Vencimento',
      start: 74,
      end: 81,
      type: 'date',
      format: 'DDMMAAAA',
      required: false,
      issueCode: 'F240_SEGT_VENC',
    },
    {
      id: 'valor',
      label: 'Valor nominal',
      start: 82,
      end: 96,
      type: 'money',
      required: false,
      issueCode: 'F240_SEGT_VALOR',
    },
    { id: 'banco_cobrador', label: 'Banco cobrador', start: 97, end: 99, type: 'numeric', required: false },
    { id: 'agencia_cobradora', label: 'Agência cobradora', start: 100, end: 104, type: 'numeric', required: false },
    { id: 'dv_agencia_cob', label: 'DV agência cobradora', start: 105, end: 105, type: 'alphanumeric', required: false },
    { id: 'uso_empresa', label: 'Identificação título empresa', start: 106, end: 130, type: 'alphanumeric', required: false },
    { id: 'codigo_moeda', label: 'Código moeda', start: 131, end: 132, type: 'numeric', required: false },
    { id: 'tipo_inscricao', label: 'Tipo inscrição pagador', start: 133, end: 133, type: 'enum', enum: ['1', '2', '0', ' '], required: false },
    { id: 'cpf_cnpj', label: 'CPF/CNPJ pagador', start: 134, end: 148, type: 'numeric', required: false },
    { id: 'nome_pagador', label: 'Nome pagador', start: 149, end: 188, type: 'alpha', required: false },
    { id: 'numero_contrato', label: 'Nº contrato', start: 189, end: 198, type: 'alphanumeric', required: false },
    {
      id: 'valor_tarifa',
      label: 'Valor tarifa/custas',
      start: 199,
      end: 213,
      type: 'money',
      required: false,
    },
    {
      id: 'motivos',
      label: 'Motivos ocorrência',
      start: 214,
      end: 223,
      type: 'alphanumeric',
      required: false,
    },
    { id: 'resto', label: 'Uso FEBRABAN', start: 224, end: 240, type: 'filler', required: false },
  ],
}

/** Segmento U — valores liquidados (ACBr LerRetorno240) */
export const FEBRABAN_RETORNO_C240_SEGMENTO_U: RecordSpec = {
  id: 'febraban-retorno-c240-segmento-u',
  layout: 'c240',
  kind: 'retorno',
  recordType: '3U',
  label: 'Segmento U (retorno)',
  lineLength: 240,
  acbrRef: 'ACBrBoleto.pas:TACBrBancoClass.LerRetorno240 (seg U)',
  fields: [
    { id: 'codigo_banco', label: 'Código banco', start: 1, end: 3, type: 'numeric' },
    { id: 'lote', label: 'Lote', start: 4, end: 7, type: 'numeric' },
    { id: 'tipo_registro', label: 'Tipo registro', start: 8, end: 8, type: 'enum', enum: ['3'] },
    { id: 'sequencial', label: 'Sequencial lote', start: 9, end: 13, type: 'numeric' },
    { id: 'segmento', label: 'Segmento', start: 14, end: 14, type: 'enum', enum: ['U'] },
    { id: 'uso_febraban', label: 'Uso FEBRABAN', start: 15, end: 15, type: 'filler', required: false },
    {
      id: 'codigo_movimento',
      label: 'Código movimento',
      start: 16,
      end: 17,
      type: 'enum',
      enumRef: 'febraban-retorno-240',
      issueCode: 'F240_SEGU_MOV',
      required: false,
    },
    { id: 'juros_multa', label: 'Juros/multa/encargos', start: 18, end: 32, type: 'money', required: false },
    { id: 'valor_desconto', label: 'Valor desconto', start: 33, end: 47, type: 'money', required: false },
    { id: 'valor_abatimento', label: 'Valor abatimento', start: 48, end: 62, type: 'money', required: false },
    { id: 'valor_iof', label: 'Valor IOF', start: 63, end: 77, type: 'money', required: false },
    { id: 'valor_pago', label: 'Valor pago pelo pagador', start: 78, end: 92, type: 'money', required: false, issueCode: 'F240_SEGU_PAGO' },
    { id: 'valor_liquido', label: 'Valor líquido creditado', start: 93, end: 107, type: 'money', required: false },
    { id: 'outras_despesas', label: 'Outras despesas', start: 108, end: 122, type: 'money', required: false },
    { id: 'outros_creditos', label: 'Outros créditos', start: 123, end: 137, type: 'money', required: false },
    {
      id: 'data_ocorrencia',
      label: 'Data ocorrência',
      start: 138,
      end: 145,
      type: 'date',
      format: 'DDMMAAAA',
      required: false,
      issueCode: 'F240_SEGU_DATA_OCORR',
    },
    {
      id: 'data_credito',
      label: 'Data crédito',
      start: 146,
      end: 153,
      type: 'date',
      format: 'DDMMAAAA',
      required: false,
    },
    { id: 'resto', label: 'Demais campos U', start: 154, end: 240, type: 'filler', required: false },
  ],
}

export const FEBRABAN_RETORNO_C240_TRAILER_LOTE: RecordSpec = {
  id: 'febraban-retorno-c240-trailer-lote-0001',
  layout: 'c240',
  kind: 'retorno',
  recordType: '0001-5',
  label: 'Trailer lote CNAB240 Retorno',
  lineLength: 240,
  fields: [
    { id: 'codigo_banco', label: 'Código banco', start: 1, end: 3, type: 'numeric' },
    { id: 'lote', label: 'Lote', start: 4, end: 7, type: 'numeric' },
    { id: 'tipo_registro', label: 'Tipo registro', start: 8, end: 8, type: 'enum', enum: ['5'] },
    { id: 'uso_febraban', label: 'Uso FEBRABAN', start: 9, end: 17, type: 'filler', required: false },
    { id: 'qtd_registros', label: 'Qtd registros lote', start: 18, end: 23, type: 'numeric', required: false },
    { id: 'resto', label: 'Totais/resto', start: 24, end: 240, type: 'filler', required: false },
  ],
}

export const FEBRABAN_RETORNO_C240_TRAILER_ARQ: RecordSpec = {
  id: 'febraban-retorno-c240-trailer-arquivo-9999',
  layout: 'c240',
  kind: 'retorno',
  recordType: '9999-9',
  label: 'Trailer arquivo CNAB240 Retorno',
  lineLength: 240,
  fields: [
    { id: 'codigo_banco', label: 'Código banco', start: 1, end: 3, type: 'numeric' },
    { id: 'lote', label: 'Lote', start: 4, end: 7, type: 'enum', enum: ['9999'] },
    { id: 'tipo_registro', label: 'Tipo registro', start: 8, end: 8, type: 'enum', enum: ['9'] },
    { id: 'uso_febraban', label: 'Uso FEBRABAN', start: 9, end: 17, type: 'filler', required: false },
    { id: 'qtd_lotes', label: 'Qtd lotes', start: 18, end: 23, type: 'numeric', required: false },
    { id: 'qtd_registros', label: 'Qtd registros', start: 24, end: 29, type: 'numeric', required: false },
    { id: 'resto', label: 'Uso exclusivo', start: 30, end: 240, type: 'filler', required: false },
  ],
}

export const FEBRABAN_RETORNO_C240_SPECS: RecordSpec[] = [
  FEBRABAN_RETORNO_C240_HEADER_ARQ,
  FEBRABAN_RETORNO_C240_HEADER_LOTE,
  FEBRABAN_RETORNO_C240_SEGMENTO_T,
  FEBRABAN_RETORNO_C240_SEGMENTO_U,
  FEBRABAN_RETORNO_C240_TRAILER_LOTE,
  FEBRABAN_RETORNO_C240_TRAILER_ARQ,
]
