import type { RecordSpec } from '../../../types'

/** Header CNAB400 retorno — gate ACBr 02RETORNO */
export const FEBRABAN_RETORNO_C400_HEADER_0: RecordSpec = {
  id: 'febraban-retorno-c400-header-0',
  layout: 'c400',
  kind: 'retorno',
  recordType: '0',
  label: 'Header CNAB400 Retorno',
  lineLength: 400,
  acbrRef: 'ACBrBoleto.pas:TACBrBoleto.LerRetorno (02RETORNO)',
  fields: [
    {
      id: 'tipo_registro',
      label: 'Identificação do registro',
      start: 1,
      end: 1,
      type: 'enum',
      enum: ['0'],
      issueCode: 'F400_HDR_TIPO_REG',
    },
    {
      id: 'tipo_arquivo',
      label: 'Identificação arquivo retorno',
      start: 2,
      end: 2,
      type: 'enum',
      enum: ['2'],
      issueCode: 'F400_HDR_TIPO_ARQ',
    },
    {
      id: 'literal_retorno',
      label: 'Literal RETORNO',
      start: 3,
      end: 9,
      type: 'enum',
      enum: ['RETORNO'],
      issueCode: 'F400_HDR_LITERAL',
    },
    {
      id: 'codigo_servico',
      label: 'Código serviço',
      start: 10,
      end: 11,
      type: 'enum',
      enum: ['01'],
    },
    {
      id: 'literal_servico',
      label: 'Literal serviço',
      start: 12,
      end: 26,
      type: 'alpha',
      required: false,
    },
    {
      id: 'codigo_empresa',
      label: 'Código da empresa no banco',
      start: 27,
      end: 46,
      type: 'alphanumeric',
      bankOverride: true,
      required: false,
    },
    {
      id: 'nome_empresa',
      label: 'Nome da empresa',
      start: 47,
      end: 76,
      type: 'alpha',
      required: false,
    },
    {
      id: 'codigo_banco',
      label: 'Código do banco',
      start: 77,
      end: 79,
      type: 'numeric',
      pad: 'numeric',
      issueCode: 'F400_HDR_BANCO',
    },
    {
      id: 'nome_banco',
      label: 'Nome do banco',
      start: 80,
      end: 94,
      type: 'alpha',
      required: false,
    },
    {
      id: 'data_geracao',
      label: 'Data gravação',
      start: 95,
      end: 100,
      type: 'date',
      format: 'DDMMAA',
      issueCode: 'F400_HDR_DATA',
      required: false,
    },
    {
      id: 'brancos_101',
      label: 'Brancos',
      start: 101,
      end: 107,
      type: 'filler',
      required: false,
    },
    {
      id: 'densidade',
      label: 'Densidade / brancos',
      start: 108,
      end: 110,
      type: 'alphanumeric',
      required: false,
    },
    {
      id: 'numero_arquivo',
      label: 'Número sequencial arquivo',
      start: 111,
      end: 117,
      type: 'numeric',
      pad: 'numeric',
      required: false,
    },
    {
      id: 'brancos_118',
      label: 'Brancos',
      start: 118,
      end: 394,
      type: 'filler',
      required: false,
    },
    {
      id: 'sequencial',
      label: 'Sequencial registro',
      start: 395,
      end: 400,
      type: 'numeric',
      pad: 'numeric',
      issueCode: 'F400_HDR_SEQ',
    },
  ],
}

/** Detalhe CNAB400 retorno — ocorrência CodOcorrenciaToTipo (pos 109–110) */
export const FEBRABAN_RETORNO_C400_DETALHE_1: RecordSpec = {
  id: 'febraban-retorno-c400-detalhe-1',
  layout: 'c400',
  kind: 'retorno',
  recordType: '1',
  label: 'Detalhe CNAB400 Retorno',
  lineLength: 400,
  acbrRef: 'ACBrBoleto.pas:TACBrBancoClass.LerRetorno400',
  fields: [
    { id: 'tipo_registro', label: 'Tipo registro', start: 1, end: 1, type: 'enum', enum: ['1'], issueCode: 'F400_DET_TIPO' },
    {
      id: 'ocorrencia',
      label: 'Código ocorrência',
      start: 109,
      end: 110,
      type: 'enum',
      enumRef: 'febraban-retorno-400',
      issueCode: 'F400_DET_OCORR',
    },
    {
      id: 'data_ocorrencia',
      label: 'Data ocorrência',
      start: 111,
      end: 116,
      type: 'date',
      format: 'DDMMAA',
      required: false,
      issueCode: 'F400_RET_DATA_OCORR',
    },
    {
      id: 'numero_documento',
      label: 'Número documento',
      start: 117,
      end: 126,
      type: 'alphanumeric',
      required: false,
    },
    {
      id: 'valor_titulo',
      label: 'Valor título',
      start: 153,
      end: 165,
      type: 'money',
      required: false,
      issueCode: 'F400_RET_VALOR',
    },
    {
      id: 'valor_pago',
      label: 'Valor pago',
      start: 254,
      end: 266,
      type: 'money',
      required: false,
    },
    {
      id: 'data_credito',
      label: 'Data crédito',
      start: 296,
      end: 301,
      type: 'date',
      format: 'DDMMAA',
      required: false,
    },
    {
      id: 'motivos',
      label: 'Motivos ocorrência',
      start: 319,
      end: 328,
      type: 'alphanumeric',
      required: false,
    },
    {
      id: 'sequencial',
      label: 'Sequencial',
      start: 395,
      end: 400,
      type: 'numeric',
      pad: 'numeric',
      issueCode: 'F400_DET_SEQ',
    },
  ],
}

export const FEBRABAN_RETORNO_C400_TRAILER_9: RecordSpec = {
  id: 'febraban-retorno-c400-trailer-9',
  layout: 'c400',
  kind: 'retorno',
  recordType: '9',
  label: 'Trailer CNAB400 Retorno',
  lineLength: 400,
  fields: [
    {
      id: 'tipo_registro',
      label: 'Identificação do registro',
      start: 1,
      end: 1,
      type: 'enum',
      enum: ['9'],
      issueCode: 'F400_TRL_TIPO',
    },
    {
      id: 'brancos',
      label: 'Brancos',
      start: 2,
      end: 394,
      type: 'filler',
      required: false,
    },
    {
      id: 'sequencial',
      label: 'Sequencial registro',
      start: 395,
      end: 400,
      type: 'numeric',
      pad: 'numeric',
      issueCode: 'F400_TRL_SEQ',
    },
  ],
}

export const FEBRABAN_RETORNO_C400_SPECS: RecordSpec[] = [
  FEBRABAN_RETORNO_C400_HEADER_0,
  FEBRABAN_RETORNO_C400_DETALHE_1,
  FEBRABAN_RETORNO_C400_TRAILER_9,
]
