import type { RecordSpec } from '../../../../types'

/** Detalhe CNAB400 Bradesco — ACBrBancoBradesco.GerarLinhaRegistroTransacao400 */
export const BRADESCO_C400_DETALHE_1: RecordSpec = {
  id: 'cobBradesco-c400-detalhe-1',
  layout: 'c400',
  recordType: '1',
  label: 'Detalhe Bradesco CNAB400',
  lineLength: 400,
  bankId: 'cobBradesco',
  acbrRef: 'ACBrBancoBradesco.pas:GerarLinhaRegistroTransacao400',
  fields: [
    { id: 'tipo_registro', label: 'Tipo registro', start: 1, end: 1, type: 'enum', enum: ['1'], issueCode: 'F400_DET_TIPO' },
    { id: 'debito_auto', label: 'Débito automático', start: 2, end: 20, type: 'filler', required: false },
    { id: 'carteira_ag_conta', label: 'Carteira/Ag/Conta', start: 21, end: 37, type: 'alphanumeric' },
    { id: 'controle_participante', label: 'Controle participante', start: 38, end: 65, type: 'alphanumeric', required: false },
    { id: 'multa_ind', label: 'Indicador multa', start: 66, end: 66, type: 'enum', enum: ['0', '2'], required: false },
    { id: 'multa_pct', label: '% multa', start: 67, end: 70, type: 'numeric', required: false },
    { id: 'nosso_numero', label: 'Nosso número', start: 71, end: 82, type: 'alphanumeric', issueCode: 'F400_BRAD_NOSSO_NUM' },
    { id: 'desconto_dia', label: 'Desconto bonificação/dia', start: 83, end: 92, type: 'numeric', required: false },
    { id: 'tipo_emissao', label: 'Tipo emissão/distribuição', start: 93, end: 104, type: 'alphanumeric', required: false },
    { id: 'instrucoes', label: 'Rateio/aviso/ocorrência', start: 105, end: 108, type: 'alphanumeric', required: false },
    {
      id: 'ocorrencia',
      label: 'Código ocorrência',
      start: 109,
      end: 110,
      type: 'enum',
      enumRef: 'bradesco-remessa-400',
      issueCode: 'F400_BRAD_OCORR',
    },
    { id: 'numero_documento', label: 'Número documento', start: 111, end: 120, type: 'alphanumeric', issueCode: 'F400_DET_DOC' },
    { id: 'vencimento', label: 'Vencimento', start: 121, end: 126, type: 'date', format: 'DDMMAA', issueCode: 'F400_DET_VENC' },
    { id: 'valor', label: 'Valor título', start: 127, end: 139, type: 'money', issueCode: 'F400_DET_VALOR' },
    { id: 'banco_cobrador', label: 'Banco cobrador/espécie', start: 140, end: 150, type: 'alphanumeric', required: false },
    { id: 'data_emissao', label: 'Data emissão', start: 151, end: 156, type: 'date', format: 'DDMMAA', required: false },
    { id: 'protesto', label: 'Instruções protesto', start: 157, end: 160, type: 'alphanumeric', required: false },
    { id: 'mora', label: 'Mora/dia', start: 161, end: 173, type: 'money', required: false },
    { id: 'data_desconto', label: 'Data desconto', start: 174, end: 179, type: 'date', format: 'DDMMAA', required: false },
    { id: 'valor_desconto', label: 'Valor desconto', start: 180, end: 192, type: 'money', required: false },
    { id: 'iof', label: 'IOF', start: 193, end: 205, type: 'money', required: false },
    { id: 'abatimento', label: 'Abatimento', start: 206, end: 218, type: 'money', required: false },
    { id: 'tipo_inscricao', label: 'Tipo inscrição sacado', start: 219, end: 219, type: 'enum', enum: ['1', '2'] },
    { id: 'cpf_cnpj', label: 'CPF/CNPJ sacado', start: 220, end: 233, type: 'numeric', issueCode: 'F400_DET_CPF' },
    { id: 'nome_sacado', label: 'Nome sacado', start: 235, end: 274, type: 'alpha', issueCode: 'F400_DET_NOME' },
    { id: 'endereco', label: 'Endereço sacado', start: 275, end: 314, type: 'alpha', required: false },
    { id: 'mensagem1', label: '1ª mensagem', start: 315, end: 326, type: 'alpha', required: false },
    { id: 'cep', label: 'CEP', start: 327, end: 334, type: 'numeric', issueCode: 'F400_DET_CEP' },
    { id: 'mensagem_cedente', label: 'Mensagem/Beneficiário final', start: 335, end: 394, type: 'alpha', required: false },
    { id: 'sequencial', label: 'Sequencial', start: 395, end: 400, type: 'numeric', pad: 'numeric', issueCode: 'F400_DET_SEQ' },
  ],
}
