import type { RecordSpec } from '../../../../types'

/** Detalhe CNAB400 Itaú (carteira com registro) — ACBrBancoItau.GerarRegistroTransacao400 */
export const ITAU_C400_DETALHE_1: RecordSpec = {
  id: 'cobItau-c400-detalhe-1',
  layout: 'c400',
  recordType: '1',
  label: 'Detalhe Itaú CNAB400',
  lineLength: 400,
  bankId: 'cobItau',
  acbrRef: 'ACBrBancoItau.pas:GerarRegistroTransacao400',
  fields: [
    { id: 'tipo_registro', label: 'Tipo registro', start: 1, end: 1, type: 'enum', enum: ['1'], issueCode: 'F400_DET_TIPO' },
    { id: 'tipo_inscricao_cedente', label: 'Tipo inscrição cedente', start: 2, end: 3, type: 'enum', enum: ['01', '02', '03', '04', '09'] },
    { id: 'cnpj_cedente', label: 'CNPJ/CPF cedente', start: 4, end: 17, type: 'numeric' },
    { id: 'agencia', label: 'Agência', start: 18, end: 21, type: 'numeric' },
    { id: 'zeros_agencia', label: 'Complemento agência', start: 22, end: 23, type: 'enum', enum: ['00'] },
    { id: 'conta', label: 'Conta', start: 24, end: 28, type: 'numeric' },
    { id: 'dv_conta', label: 'DV conta', start: 29, end: 29, type: 'alphanumeric', required: false },
    { id: 'brancos_30', label: 'Brancos', start: 30, end: 33, type: 'filler', required: false },
    { id: 'instr_cancelada', label: 'Instrução cancelada', start: 34, end: 37, type: 'alphanumeric', required: false },
    { id: 'seu_numero', label: 'Seu número', start: 38, end: 62, type: 'alphanumeric', required: false },
    { id: 'nosso_numero', label: 'Nosso número', start: 63, end: 70, type: 'numeric', issueCode: 'F400_ITAU_NOSSO' },
    { id: 'qtd_moeda', label: 'Quantidade moeda variável', start: 71, end: 83, type: 'numeric', required: false },
    { id: 'carteira', label: 'Carteira', start: 84, end: 86, type: 'alphanumeric', issueCode: 'F400_ITAU_CART' },
    { id: 'uso_banco', label: 'Uso banco', start: 87, end: 107, type: 'filler', required: false },
    { id: 'codigo_carteira', label: 'Código carteira', start: 108, end: 108, type: 'enum', enum: ['I'], required: false },
    {
      id: 'ocorrencia',
      label: 'Código ocorrência',
      start: 109,
      end: 110,
      type: 'enum',
      enumRef: 'itau-remessa-400',
      issueCode: 'F400_ITAU_OCORR',
    },
    { id: 'numero_documento', label: 'Número documento', start: 111, end: 120, type: 'alphanumeric', issueCode: 'F400_DET_DOC' },
    { id: 'vencimento', label: 'Vencimento', start: 121, end: 126, type: 'date', format: 'DDMMAA', issueCode: 'F400_DET_VENC' },
    { id: 'valor', label: 'Valor título', start: 127, end: 139, type: 'money', issueCode: 'F400_DET_VALOR' },
    { id: 'codigo_banco', label: 'Código banco', start: 140, end: 142, type: 'numeric' },
    { id: 'agencia_cobradora', label: 'Agência cobradora', start: 143, end: 147, type: 'numeric', required: false },
    { id: 'especie', label: 'Espécie documento', start: 148, end: 149, type: 'numeric', required: false },
    { id: 'aceite', label: 'Aceite', start: 150, end: 150, type: 'enum', enum: ['N', 'S'], required: false },
    { id: 'data_emissao', label: 'Data emissão', start: 151, end: 156, type: 'date', format: 'DDMMAA', required: false },
    { id: 'instrucao1', label: '1ª instrução', start: 157, end: 158, type: 'numeric', required: false },
    { id: 'instrucao2', label: '2ª instrução', start: 159, end: 160, type: 'numeric', required: false },
    { id: 'mora', label: 'Mora/dia', start: 161, end: 173, type: 'money', required: false },
    { id: 'data_desconto', label: 'Data desconto', start: 174, end: 179, type: 'date', format: 'DDMMAA', required: false },
    { id: 'valor_desconto', label: 'Valor desconto', start: 180, end: 192, type: 'money', required: false },
    { id: 'iof', label: 'IOF', start: 193, end: 205, type: 'money', required: false },
    { id: 'abatimento', label: 'Abatimento', start: 206, end: 218, type: 'money', required: false },
    { id: 'tipo_inscricao', label: 'Tipo inscrição sacado', start: 219, end: 220, type: 'enum', enum: ['01', '02'] },
    { id: 'cpf_cnpj', label: 'CPF/CNPJ sacado', start: 221, end: 234, type: 'numeric', issueCode: 'F400_DET_CPF' },
    { id: 'nome_sacado', label: 'Nome sacado', start: 235, end: 264, type: 'alpha', issueCode: 'F400_DET_NOME' },
    { id: 'brancos_sacado', label: 'Brancos', start: 265, end: 274, type: 'filler', required: false },
    { id: 'endereco', label: 'Endereço sacado', start: 275, end: 314, type: 'alpha', required: false },
    { id: 'bairro', label: 'Bairro', start: 315, end: 326, type: 'alpha', required: false },
    { id: 'cep', label: 'CEP', start: 327, end: 334, type: 'numeric', issueCode: 'F400_DET_CEP' },
    { id: 'cidade', label: 'Cidade', start: 335, end: 349, type: 'alpha', required: false },
    { id: 'uf', label: 'UF', start: 350, end: 351, type: 'alpha', required: false },
    { id: 'mensagem_avalista', label: 'Mensagem/avalista', start: 352, end: 391, type: 'alpha', required: false },
    { id: 'prazo_protesto', label: 'Prazo protesto', start: 392, end: 393, type: 'numeric', required: false },
    { id: 'branco_394', label: 'Branco', start: 394, end: 394, type: 'filler', required: false },
    { id: 'sequencial', label: 'Sequencial', start: 395, end: 400, type: 'numeric', pad: 'numeric', issueCode: 'F400_DET_SEQ' },
  ],
}
